### ISSUE TITLE
ensureRoot does not actually exit if user is not root

### ISSUE THREAD

**Issue by TarzanInAJar** [Randy-Blancett/bashLibrary#30]
The following line of code will log that the user is not root

https://github.com/Randy-Blancett/bashLibrary/blob/5844eb5fcabfaef53dd0a6e0476ffcac54e95075/src/main/bash/lib/shellUtils.sh#L230-L231

Note the `|| exit 1` - it will only actually exit if the `log` for whatever reason failed, which is highly unlikely. It was probably meant to use a `&&`

**Comment by Randy-Blancett** [comment]
That is a valid point, I guess the return code would get swallowed... Good Catch

**Comment by Randy-Blancett** [comment]
Version 1.3.0 has been released and it includes the fix for this issue.
